### PR TITLE
Attempt OSX apps build (Don't merge!)

### PR DESCRIPTION
**Pull request by nosami**
Attempting to build on OSX so that we can build sample apps.

### CODE REVIEW

**Comment by dsyme** [comment]
It will be so good to have this, both for correctness and as a guide to others.

**Comment by nosami** [comment]
I'm still looking into it, it's not at all obvious how to make it all work :)

**Comment by nosami** [comment]
So, this is actually building now on OSX. Looks like some legitimate warnings and errors to fix up.

**Comment by dsyme** [comment]
OK, I pushed the necessary build fixes and we have green!! This is fantastic, thanks @nosami I could never have worked that stuff out.

**Pull request merged**
